/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlganalyzesumm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlganalyzesumm.class.getName());

    /**
     * Creates new form dldanalyzesumm
     */
    public dlganalyzesumm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcancel = new javax.swing.JButton();
        btaccept = new javax.swing.JButton();
        summsel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 212));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(470, 202));
        jPanel1.setMinimumSize(new java.awt.Dimension(470, 202));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btcancel.setText("Cancelar");
        btcancel.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 90, 30));

        btaccept.setText("Aceptar");
        btaccept.setMaximumSize(new java.awt.Dimension(76, 29));
        btaccept.setMinimumSize(new java.awt.Dimension(76, 29));
        btaccept.setPreferredSize(new java.awt.Dimension(76, 29));
        btaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptActionPerformed(evt);
            }
        });
        jPanel1.add(btaccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, 30));

        summsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(summsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione el resumen a analizar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Analizar resumen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void btacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptActionPerformed
        // TODO add your handling code here:
    String seluser = this.summsel.getSelectedItem().toString();
    if (seluser.equals("--Seleccionar--"))
    {   
        JOptionPane.showMessageDialog(null, "Debe seleccionar el usuario a eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    else  
    {
        this.dispose();
        analyzesumm ansumm = new analyzesumm();
        ansumm.setVisible(true);
    }
    }//GEN-LAST:event_btacceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlganalyzesumm dialog = new dlganalyzesumm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void fillallsum()
    {
        /**
        * Elimina todos los items de la lista de selección o ComboBox(deluser1)
        * Agrega un item al ComboBox(deluser1) llamado "--Seleccionar--" que indica que es estrictamente necesario seleccionar un usuario
        * Modifica al ComboBox(deluser1) para que solo estén los usuarios del arreglo users
        * Itera sobre todos los usuarios (nodos) del arreglo users y los agrega al ComboBox(deluser1)
        */
        this.summsel.removeAllItems();
        this.summsel.addItem("--Seleccionar--");
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaccept;
    private javax.swing.JButton btcancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> summsel;
    // End of variables declaration//GEN-END:variables
}
