/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlgauthor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgauthor.class.getName());

    /**
     * Creates new form dlgauthor
     */
    public dlgauthor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        authorsel = new javax.swing.JComboBox<>();
        listauthor = new java.awt.List();
        btaccept = new javax.swing.JButton();
        btcancel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("buscar resumen por autor");
        setMinimumSize(new java.awt.Dimension(498, 318));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 220, 154));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Buscar por autor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione el autor para ver los resumenes relacionados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        authorsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        authorsel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                authorselItemStateChanged(evt);
            }
        });
        authorsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorselActionPerformed(evt);
            }
        });
        jPanel1.add(authorsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 30));

        listauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listauthorActionPerformed(evt);
            }
        });
        jPanel1.add(listauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, 110));

        btaccept.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btaccept.setText("Detalles");
        btaccept.setMaximumSize(new java.awt.Dimension(76, 29));
        btaccept.setMinimumSize(new java.awt.Dimension(76, 29));
        btaccept.setPreferredSize(new java.awt.Dimension(76, 29));
        btaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptActionPerformed(evt);
            }
        });
        jPanel1.add(btaccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 30));

        btcancel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btcancel3.setText("Cancelar");
        btcancel3.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel3.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel3.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancel3ActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void authorselItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_authorselItemStateChanged
        // TODO add your handling code here:
        this.listauthor.removeAll();
        if(this.authorsel.getSelectedItem() != null && !"--Seleccionar--".equals(this.authorsel.getSelectedItem().toString()))
        {
            Hash Obj = new Hash();
            int hashcode = Obj.getHashCode(this.authorsel.getSelectedItem().toString());
            for(int i=0; i< Proyecto_2.Auth_Proj[hashcode].length; i++)
            {
                if(Proyecto_2.Auth_Proj[hashcode][i] != 0)
                {
                    int hashproj = Proyecto_2.Auth_Proj[hashcode][i];
                    String proj = Proyecto_2.Proj_Tit[hashproj];
                    this.listauthor.add(proj);
                }
                else
                {
                    break;
                }

            }
        }
    }//GEN-LAST:event_authorselItemStateChanged

    private void listauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listauthorActionPerformed

    private void btacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptActionPerformed
        // TODO add your handling code here:
        if (this.listauthor.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un resumen de la lista.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            this.dispose();
            analyzesumm ansumm = new analyzesumm();
            String SummSel = this.listauthor.getSelectedItem().toString();
            ansumm.fillTextArea(SummSel);
            ansumm.setVisible(true);
        }
    }//GEN-LAST:event_btacceptActionPerformed

    private void btcancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancel3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancel3ActionPerformed

    private void authorselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorselActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgauthor dialog = new dlgauthor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void fillallauthor()
    {
        /**
        * Agrega cada autor del arbol de autores (arb_author) leídos en inordes al combo box (keywordsel) incluyendo un item llamado seleccionar
        */
        String[] addauthors = Proyecto_2.arb_author.inorden(Proyecto_2.arb_author.getRaiz(), "").split(", ");
        this.authorsel.removeAllItems();
        this.authorsel.addItem("--Seleccionar--");
        for (int i=0; i<addauthors.length; i++)
        {
            this.authorsel.addItem(addauthors[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> authorsel;
    private javax.swing.JButton btaccept;
    private javax.swing.JButton btcancel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.List listauthor;
    // End of variables declaration//GEN-END:variables
}
