/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlgkeyword extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgkeyword.class.getName());

    /**
     * Creates new form dlgkeyword
     */
    public dlgkeyword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        listkey = new java.awt.List();
        btaccept = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("lista de palabras clave");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(450, 300));
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(175, 255, 167));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listkeyActionPerformed(evt);
            }
        });
        jPanel1.add(listkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 430, 160));
        listkey.getAccessibleContext().setAccessibleName("");

        btaccept.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btaccept.setText("Detalles");
        btaccept.setMaximumSize(new java.awt.Dimension(76, 29));
        btaccept.setMinimumSize(new java.awt.Dimension(76, 29));
        btaccept.setPreferredSize(new java.awt.Dimension(76, 29));
        btaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptActionPerformed(evt);
            }
        });
        jPanel1.add(btaccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, 30));

        btcancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btcancel.setText("Cancelar");
        btcancel.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Lista de palabras clave");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione una palabra clave para ver los resumenes relacionados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void listkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listkeyActionPerformed

    private void btacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptActionPerformed
        // TODO add your handling code here:
        if (this.listkey.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una palabra clave de la lista.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            dlgsearchword anword = new dlgsearchword(Proyecto_2.interf, true);
            anword.keywordsel.setEnabled(false);
            anword.keywordsel.removeAllItems();
            anword.keywordsel.addItem(this.listkey.getSelectedItem());
            anword.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btacceptActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgkeyword dialog = new dlgkeyword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void filleachkey()
    {
        this.listkey.removeAll();
        String[] addkeys = Proyecto_2.arb_keywords.inorden(Proyecto_2.arb_keywords.getRaiz(), "").split(", ");
        for (int i=0; i<addkeys.length; i++)
        {
            this.listkey.add(addkeys[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaccept;
    private javax.swing.JButton btcancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.List list1;
    private java.awt.List listkey;
    // End of variables declaration//GEN-END:variables
}
