/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlgsearchword extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgsearchword.class.getName());

    /**
     * Creates new form dlgsearchkword
     */
    public dlgsearchword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keywordsel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btaccept = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(491, 236));
        setMinimumSize(new java.awt.Dimension(491, 236));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(201, 250, 226));
        jPanel1.setMaximumSize(new java.awt.Dimension(491, 236));
        jPanel1.setMinimumSize(new java.awt.Dimension(491, 236));
        jPanel1.setPreferredSize(new java.awt.Dimension(491, 236));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keywordsel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        keywordsel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                keywordselItemStateChanged(evt);
            }
        });
        jPanel1.add(keywordsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione la palabra clave para ver los resumenes relacionados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Buscar por palabra clave");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btaccept.setText("Aceptar");
        btaccept.setMaximumSize(new java.awt.Dimension(76, 29));
        btaccept.setMinimumSize(new java.awt.Dimension(76, 29));
        btaccept.setPreferredSize(new java.awt.Dimension(76, 29));
        btaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptActionPerformed(evt);
            }
        });
        jPanel1.add(btaccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 30));

        btcancel.setText("Cancelar");
        btcancel.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, 30));

        list1.setMinimumSize(new java.awt.Dimension(72, 80));
        list1.setPreferredSize(new java.awt.Dimension(72, 80));
        jPanel1.add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptActionPerformed
        // TODO add your handling code here:
        if (this.list1.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un resumen de la lista.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            this.dispose();
            analyzesumm ansumm = new analyzesumm();
            String SummSel = this.list1.getSelectedItem().toString();
            Hash Obj = new Hash();
            int hashproj = Obj.getHashCode(SummSel);
            String SummText;
            SummText = SummSel+"\r\n\r\n";
            SummText += "Autores\r\n";
            for(int i=0; i<Proyecto_2.Proj_Auth[hashproj].length; i++)
            {
                if(Proyecto_2.Proj_Auth[hashproj][i]!=0)
                {
                    int hashauth = Proyecto_2.Proj_Auth[hashproj][i];
                    SummText += Proyecto_2.Auth[hashauth] + "\r\n";
                }
                else break;
            }
            SummText += "\r\nResumen\r\n";
            SummText += Proyecto_2.Proj_Sum[hashproj]+"\r\n";
            SummText += "\r\nPalabras claves: ";
            for(int i=0; i<Proyecto_2.Proj_Key[hashproj].length; i++)
            {
                if(Proyecto_2.Proj_Key[hashproj][i]!=0)
                {
                    int hashkey = Proyecto_2.Proj_Key[hashproj][i];
                    if(i>0)
                    {
                        SummText += ", ";
                    }
                    SummText += Proyecto_2.Key[hashkey].trim();
                }
                else break;
            }
            ansumm.textansumm.setText(SummText);
            ansumm.setVisible(true);
        }
    }//GEN-LAST:event_btacceptActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void keywordselItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_keywordselItemStateChanged
        // TODO add your handling code here:
        this.list1.removeAll();
        if(this.keywordsel.getSelectedItem() != null && !"--Seleccionar--".equals(this.keywordsel.getSelectedItem().toString()))
        {
            Hash Obj = new Hash();
            int hashcode = Obj.getHashCode(this.keywordsel.getSelectedItem().toString());
            for(int i=0; i< Proyecto_2.Key_Proj[hashcode].length; i++)
            {
                if(Proyecto_2.Key_Proj[hashcode][i] != 0)
                {
                    int hashproj = Proyecto_2.Key_Proj[hashcode][i];
                    String proj = Proyecto_2.Proj_Tit[hashproj];
                    this.list1.add(proj);
                }
                else
                {
                    break;
                }
                
            }
        }
        

    }//GEN-LAST:event_keywordselItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgsearchword dialog = new dlgsearchword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void fillallkey()
    {
        /**
        * Elimina todos los items de la lista de selección o ComboBox(deluser1)
        * Agrega un item al ComboBox(deluser1) llamado "--Seleccionar--" que indica que es estrictamente necesario seleccionar un usuario
        * Modifica al ComboBox(deluser1) para que solo estén los usuarios del arreglo users
        * Itera sobre todos los usuarios (nodos) del arreglo users y los agrega al ComboBox(deluser1)
        */
        String[] addKey = new String[0];
        String[] tmpKey = new String[0];
        this.keywordsel.removeAllItems();
        this.keywordsel.addItem("--Seleccionar--");
        for(int i=0; i<Proyecto_2.Key_Proj.length;i++)
        {
            if(Proyecto_2.Key[i]!=null)
            {
                tmpKey = new String[addKey.length + 1];
                for(int j=0; j<addKey.length;j++)
                {
                    tmpKey[j] = addKey[j];
                }
                tmpKey[tmpKey.length - 1] = Proyecto_2.Key[i];
                addKey = tmpKey;
            }  
        }
        tmpKey = Proyecto_2.OrderStringArray(addKey);
        for(int i=0; i<tmpKey.length; i++)
        {
            this.keywordsel.addItem(tmpKey[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaccept;
    private javax.swing.JButton btcancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> keywordsel;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
