/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_2;

/**
 *
 * @author Daniela
 */
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnBuscaClave = new javax.swing.JButton();
        btinBuscaAutor = new javax.swing.JButton();
        btinBuscaAutor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("repositorio de resumenes");

        jPanel1.setBackground(new java.awt.Color(225, 213, 225));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 373));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 373));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 373));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(145, 83));
        btnSalir.setMinimumSize(new java.awt.Dimension(145, 83));
        btnSalir.setPreferredSize(new java.awt.Dimension(145, 83));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel1.setText("Repositorio de resumenes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/Agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar resumen");
        btnAgregar.setPreferredSize(new java.awt.Dimension(290, 83));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnAnalizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/Analizar.png"))); // NOI18N
        btnAnalizar.setText("Analizar resumen");
        btnAnalizar.setPreferredSize(new java.awt.Dimension(290, 83));
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btnBuscaClave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscaClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/BuscaClave.png"))); // NOI18N
        btnBuscaClave.setText("Buscar resumen por palabra clave");
        btnBuscaClave.setMaximumSize(new java.awt.Dimension(290, 83));
        btnBuscaClave.setMinimumSize(new java.awt.Dimension(290, 83));
        btnBuscaClave.setPreferredSize(new java.awt.Dimension(290, 83));
        btnBuscaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        btinBuscaAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btinBuscaAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/BuscaAutor.png"))); // NOI18N
        btinBuscaAutor.setText("Buscar resumen por autor");
        btinBuscaAutor.setPreferredSize(new java.awt.Dimension(290, 83));
        btinBuscaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinBuscaAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btinBuscaAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btinBuscaAutor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btinBuscaAutor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_2/ListarClaves.png"))); // NOI18N
        btinBuscaAutor1.setText("Lista de palabras clave");
        btinBuscaAutor1.setPreferredSize(new java.awt.Dimension(290, 83));
        btinBuscaAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinBuscaAutor1ActionPerformed(evt);
            }
        });
        jPanel1.add(btinBuscaAutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClaveActionPerformed
        // TODO add your handling code here:
        dlgsearchword buscarpal = new dlgsearchword(this, true);
        buscarpal.fillallkey();
        buscarpal.setVisible(true);
    }//GEN-LAST:event_btnBuscaClaveActionPerformed

    private void btinBuscaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinBuscaAutorActionPerformed
        // TODO add your handling code here:
        dlgauthor dlautor = new dlgauthor(this, true);
        dlautor.fillallauthor();
        dlautor.setVisible(true);
    }//GEN-LAST:event_btinBuscaAutorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter txtonly = new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.setFileFilter(txtonly);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = jfc.getSelectedFile();
            Boolean FileLoaded = LoadDefault.LoadSummary(selectedFile);
            if(FileLoaded)
            {
                LoadDefault.SaveData();
                JOptionPane.showMessageDialog(null, "El resumen ha sido agregado exitosamente", "AGREGADO", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Formato del archivo inválido o Resumen ya agregado", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btinBuscaAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinBuscaAutor1ActionPerformed
        // TODO add your handling code here:
        dlgkeyword dlpalcla = new dlgkeyword(this, true);
        dlpalcla.filleachkey();
        dlpalcla.setVisible(true);
    }//GEN-LAST:event_btinBuscaAutor1ActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        dlganalyzesumm selresum = new dlganalyzesumm(this, true);
        selresum.fillallsum();
        selresum.setVisible(true);
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btinBuscaAutor;
    private javax.swing.JButton btinBuscaAutor1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnBuscaClave;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
